version: "3.9"
services:
  postgres-master:
    env_file: .env
    image: postgres:15
    container_name: email-sender-postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - ../email-sender-postgres-data:/var/lib/postgresql/data
      - ./migration:/opt/migration
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - services
  rabbit:
    image: rabbitmq:management
    restart: always
    # env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./shared-files/rabbitmq:/var/lib/rabbitmq
    networks:
      - services
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - services

networks:
  services:
    driver: bridge